import { motion } from "framer-motion";
import { Brain, ChartColumnBig, Cpu, Gem, Shield, Sparkles } from "lucide-react";

const sections = [
  {
    title: "Platform Overview",
    body: "CryptoPulse is an AI-powered fintech analytics platform for real-time market intelligence, predictive modeling, and sentiment-driven decision support.",
    icon: ChartColumnBig,
  },
  {
    title: "Mission & Vision",
    body: "Our mission is to democratize institutional-grade crypto analytics. We aim to make AI market intelligence accessible, explainable, and actionable for every trader.",
    icon: Gem,
  },
  {
    title: "How AI Forecasting Works",
    body: "Forecasts are generated by Facebook Prophet from historical OHLC data, then enriched with technical and sentiment features before being ranked with confidence scoring.",
    icon: Brain,
  },
  {
    title: "Technologies",
    body: "React, Tailwind CSS, Node.js/Express, MongoDB, Facebook Prophet, VADER sentiment, Stripe payments, and modular API services power the platform.",
    icon: Cpu,
  },
  {
    title: "Architecture",
    body: "A decoupled frontend + API + AI engine architecture ensures scalability, maintainability, and fast feature delivery.",
    icon: Shield,
  },
];

export default function AboutPage() {
  return (
    <div className="min-h-screen bg-[#050010] text-white px-4 py-24 md:px-8">
      <div className="max-w-7xl mx-auto space-y-10">
        <div className="text-center">
          <p className="text-xs uppercase tracking-wide text-purple-300">About CryptoPulse</p>
          <h1 className="text-4xl font-black mt-2">Professional AI Crypto Intelligence</h1>
          <p className="text-gray-400 mt-3 max-w-3xl mx-auto">
            Built as a production-grade fintech analytics platform with explainable AI forecasting and sentiment-aware market insights.
          </p>
        </div>

        <div className="grid gap-5 md:grid-cols-2">
          {sections.map(({ title, body, icon: Icon }, index) => (
            <motion.div key={title}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: index * 0.05 }}
              className="rounded-2xl border border-white/10 bg-white/[0.03] p-5">
              <p className="inline-flex items-center gap-2 text-sm font-semibold text-purple-300">
                <Icon size={14} /> {title}
              </p>
              <p className="mt-3 text-sm text-gray-300 leading-relaxed">{body}</p>
            </motion.div>
          ))}
        </div>

        <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-6">
          <h2 className="text-2xl font-bold">Benefits</h2>
          <div className="mt-4 grid gap-3 md:grid-cols-3 text-sm text-gray-300">
            <p className="rounded-xl border border-white/10 bg-white/5 p-3">Explainable predictions, not black-box outputs</p>
            <p className="rounded-xl border border-white/10 bg-white/5 p-3">Integrated sentiment and technical context</p>
            <p className="rounded-xl border border-white/10 bg-white/5 p-3">Modern dashboards designed for speed and clarity</p>
          </div>
        </div>

        <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-6">
          <h2 className="text-2xl font-bold">Architecture Strength Metrics</h2>
          <div className="mt-4 space-y-3">
            {[
              { label: "Forecast Explainability", value: 88 },
              { label: "Realtime Responsiveness", value: 82 },
              { label: "Modular Scalability", value: 91 },
            ].map((metric) => (
              <div key={metric.label}>
                <div className="flex items-center justify-between text-sm mb-1">
                  <span className="text-gray-300">{metric.label}</span>
                  <span className="text-purple-300">{metric.value}%</span>
                </div>
                <div className="h-2 rounded-full bg-white/10 overflow-hidden">
                  <div className="h-full bg-linear-to-r from-purple-500 to-pink-500" style={{ width: `${metric.value}%` }} />
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-6">
          <h2 className="text-2xl font-bold">Roadmap Timeline</h2>
          <div className="mt-4 grid gap-3 md:grid-cols-4 text-sm">
            {[
              "Q2: Expanded multi-asset coverage",
              "Q3: Portfolio-level risk analytics",
              "Q4: Strategy backtesting studio",
              "Q1: AI anomaly detection and alerts",
            ].map((item) => (
              <div key={item} className="rounded-xl border border-white/10 bg-white/5 p-3 text-gray-300">{item}</div>
            ))}
          </div>
        </div>

        <div className="rounded-2xl border border-purple-500/30 bg-purple-500/10 p-6">
          <h2 className="text-xl font-bold flex items-center gap-2"><Sparkles size={16} /> Team / Creator</h2>
          <p className="text-sm text-gray-300 mt-2">
            CryptoPulse is engineered as a full-stack AI fintech system with production-ready design, modular architecture, and iterative model improvements.
          </p>
        </div>
      </div>
    </div>
  );
}

